pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('DB') {
      agent {
        docker { image 'mysql:8.0' }
      }
      steps {
        sh 'mysql -V'
      }
  }
   stage('Build and Run') {
      steps {
        script {
                    // Define the Java source code
                    def javaCode = '''
                        public class HelloWorld {
                            public static void main(String[] args) {
                                System.out.println("Hello, World!");
                            }
                        }
                    '''

                    // Write the Java code to a file
                    writeFile file: 'HelloWorld.java', text: javaCode

                    // Compile the Java code
                    bat 'javac HelloWorld.java'

                    // Run the Java program
                    bat 'java HelloWorld'
                }
            }
        }
    }
}
